"""Generate the checked-in Lance 2.0 compatibility fixture with official tooling."""

from __future__ import annotations

import hashlib
import json
import shutil
from base64 import b64encode
from pathlib import Path

import lance
import pyarrow as pa


ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "fixtures" / "take-v2.0.lance"
WORKERD_MODULE = ROOT / "src" / "fixture.generated.ts"


def rows() -> list[dict[str, object]]:
    return [
        {
            "serial": 10_000_000 + index,
            "mark_text": None if index in {9, 41} else f"MARK {index:03d}",
            "owner_name": f"Owner {index % 7}",
            "status": ("LIVE", "DEAD", "PENDING")[index % 3],
            "source_url": f"https://example.test/marks/{10_000_000 + index}",
            "score": index * 0.25,
            "active": index % 2 == 0,
        }
        for index in range(64)
    ]


def main() -> None:
    if FIXTURE.exists():
        shutil.rmtree(FIXTURE)
    table = pa.Table.from_pylist(
        rows(),
        schema=pa.schema(
            [
                pa.field("serial", pa.int64(), nullable=False),
                pa.field("mark_text", pa.string()),
                pa.field("owner_name", pa.string()),
                pa.field("status", pa.string()),
                pa.field("source_url", pa.string()),
                pa.field("score", pa.float64()),
                pa.field("active", pa.bool_()),
            ]
        ),
    )
    dataset = lance.write_dataset(
        table,
        FIXTURE,
        mode="create",
        data_storage_version="2.0",
        enable_stable_row_ids=True,
        enable_v2_manifest_paths=True,
        max_rows_per_file=16,
        max_rows_per_group=8,
    )
    expected = {
        "producer": {"package": "pylance", "version": lance.__version__},
        "storageVersion": dataset.data_storage_version,
        "datasetVersion": dataset.version,
        "rowCount": len(rows()),
        "rowIds": [
            str(value)
            for value in dataset.scanner(columns=["serial"], with_row_id=True)
            .to_table()
            .column("_rowid")
            .to_pylist()
        ],
        "sampleProjection": {
            "rowIds": ["31", "0", "31", "47", "9"],
            "select": ["serial", "mark_text", "owner_name", "status", "source_url"],
            "rows": [rows()[index] for index in [31, 0, 31, 47, 9]],
        },
    }
    expected["sampleProjection"]["rows"] = [
        {column: row[column] for column in expected["sampleProjection"]["select"]}
        for row in expected["sampleProjection"]["rows"]
    ]
    expected["sha256"] = {
        str(path.relative_to(FIXTURE)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(FIXTURE.rglob("*"))
        if path.is_file()
    }
    (FIXTURE / "expected.json").write_text(
        json.dumps(expected, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    files = {
        f"fixtures/take-v2.0.lance/{path.relative_to(FIXTURE)}": b64encode(
            path.read_bytes()
        ).decode("ascii")
        for path in sorted(FIXTURE.rglob("*"))
        if path.is_file() and path.name != "expected.json"
    }
    entries = "\n".join(
        f"  {json.dumps(path)}: {json.dumps(encoded)},"
        for path, encoded in files.items()
    )
    WORKERD_MODULE.write_text(
        "/* Generated by scripts/generate_fixture.py. */\n"
        "export const WORKERD_FIXTURE_BASE64: Readonly<Record<string, string>> = {\n"
        f"{entries}\n"
        "};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
